export const HAY_TYPES = [
  "#1 Alfalfa",
  "#2 Alfalfa",
  "#1 Bermuda",
  "#2 Bermuda",
  "Alfalfa grass mix",
  "Cow hay",
  "Sudan grass",
  "Triticale",
  "Oats",
  "Wheat",
  "Barley",
  "Rye",
  "4 Way Mix",
  "Corn stalks",
  "Milo stalks",
  "Timothy",
  "Orchard grass",
  "Other",
] as const
